{% set name = "jc" %}
{% set version = "1.17.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

# source:
#   url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
#   sha256: 0ded7234ec0ab648724b1bff78ef71c0b078feed462f2bd2a3e34f3cdf040728

build:
  number: 0
  entry_points:
    - jc=jc.cli:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - pygments >=2.3.0
    - python
    - ruamel.yaml >=0.15.0
    - xmltodict >=0.12.0
  run:
    - pygments >=2.3.0
    - python
    - ruamel.yaml >=0.15.0
    - xmltodict >=0.12.0

test:
  imports:
    - jc
    - jc.parsers
  commands:
    - jc -h

about:
  home: "https://github.com/kellyjonbrazil/jc"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Converts the output of popular command-line tools and file-types to JSON."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
