{% set name = "cogapp" %}
{% set version = "3.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 1be95183f70282422d594fa42426be6923070a4bd8335621f6347f3aeee81db0

build:
  number: 0
  entry_points:
    - cog = cogapp:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - cogapp
  commands:
    - cog -h

about:
  home: "http://nedbatchelder.com/code/cog"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Cog: A content generator for executing Python snippets in source files."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
