package:
  name: ridgepole
  version: "2.0.3"

source:
  path: .

build:
  script: |
    #!/bin/bash
    # unfortunately to make gems get detected properly by conda this strange workaround is required
    export GEM_HOME="$(gem env home)"
    export GEM_PATH="$GEM_HOME"
    # TODO: embed the ridgepole version number
    gem install ridgepole pg
    ln -s "$PREFIX/bin/ruby" "$GEM_HOME/bin/ruby" 
    ln -s "$PREFIX/share/rubygems/bin/ridgepole" "$PREFIX/bin/ridgepole" 

requirements:
  build:
    - ruby
    - compilers
    - make
    - autoconf
    - automake
    - libtool
    - pkg-config
    - postgresql
  run:
    - ruby
    - postgresql

about:
  home: "https://github.com/winebarrel/ridgepole"
  license: "MIT"
  summary: "Ridgepole is a tool to manage a database schema using a DSL."

extra:
  recipe-maintainers:
    - nikvdp
